apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loadtest
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: . ; ../../../common-base/platform-loadtest 
spec:
  destination:
    namespace: develop
    server: https://kubernetes.default.svc
  project: tenant
  source:
    path: loadtest-app/overlays/dev
    repoURL: https://github.com/omnidark/sandbox
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true