apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: search-dev
  namespace: elastic-system-dev
spec:
  version: 7.4.2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - count: 1
    name: master-nodes
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 1650Mi
            limits:
              memory: 1650Mi
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 32Gi
          storageClassName: managed-premium  