apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: elastic-webhook.k8s.elastic.co
webhooks:
  - clientConfig:
      caBundle: null
    name: elastic-es-validation-v1.k8s.elastic.co
  - clientConfig:
      caBundle: null
    name: elastic-es-validation-v1beta1.k8s.elastic.co
