apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa
namePrefix: sandbox-
commonLabels:
  instance: sandbox

resources:
- ../../resources

configMapGenerator:
- name: db-config
  literals:
    - VC_DB_HOST=test.com

vars:
- name: VC_DB_HOST
  objref:
    kind: ConfigMap
    name: db-config
    apiVersion: v1
  fieldref:
    fieldpath: data['VC_DB_HOST']
